/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_school21_smartcalc_NativeCalls */

#ifndef _Included_edu_school21_smartcalc_NativeCalls
#define _Included_edu_school21_smartcalc_NativeCalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_school21_smartcalc_NativeCalls
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_school21_smartcalc_NativeCalls_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
