/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "Controller/controller.h"
/* Header for class edu_school21_smartcalc_presenter_NativeLibraryCalls */

#ifndef _Included_edu_school21_smartcalc_presenter_NativeLibraryCalls
#define _Included_edu_school21_smartcalc_presenter_NativeLibraryCalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_school21_smartcalc_presenter_NativeLibraryCalls
 * Method:    calculate
 * Signature: (Ljava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL
Java_edu_school21_smartcalc_presenter_NativeLibraryCalls_calculate(JNIEnv *,
                                                                   jclass,
                                                                   jstring,
                                                                   jdouble);

/*
 * Class:     edu_school21_smartcalc_presenter_NativeLibraryCalls
 * Method:    getResult
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL
Java_edu_school21_smartcalc_presenter_NativeLibraryCalls_getResult(JNIEnv *,
                                                                   jclass);

/*
 * Class:     edu_school21_smartcalc_presenter_NativeLibraryCalls
 * Method:    checkExpressionCorrectness
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_edu_school21_smartcalc_presenter_NativeLibraryCalls_checkExpressionCorrectness(
    JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
